### ISSUE TITLE
Clarify UI useage

### ISSUE THREAD

**Issue by crazy4groovy** [camwiegert/in-view#15]
In the readme, it's not so clear how to quickly include this lib via an HTML page. Something like

`<script src="https://cdnjs.cloudflare.com/ajax/libs/in-view/0.11.5/in-view.js"></script>`

Would be much helpfulness!

**Comment by camwiegert** [comment]
Hey @crazy4groovy, thanks for the input. In the README, we currently say:

> Either download the latest release and include it in your markup

There's a link to download the latest release. in-view isn't currently on any CDN, so you'd have to host it yourself.

**Comment by crazy4groovy** [comment]
:+1:
