### ISSUE TITLE
window.innerHeight and window.innerWidth should be cached

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/in-view#19]
Currently, in-view grabs innerHeight and innerWidth on every call to inViewport. We should cache that, update on resize, and pass it to inViewport as an argument.

``` js
export function inViewport (element, offset = 0) {

    let { top, right, bottom, left } = element.getBoundingClientRect();

    return bottom > offset
        && right > offset
        && window.innerWidth - left > offset
        && window.innerHeight - top > offset;

}
```

**Comment by imvetri** [comment]
Should we cache only when triggers are scroll and load? For resize anyways it needs to be recalculated.

I was referring to https://github.com/camwiegert/in-view/blob/master/src/in-view.js#L12
`    const triggers  = ['scroll', 'resize', 'load'];`

**Comment by camwiegert** [comment]
@imvetri Yeah, definitely cached on everything but `resize`.
