### ISSUE TITLE
Allow passing a specific container

### ISSUE THREAD

**Issue by vvo** [camwiegert/in-view#20]
It's important for a library like in-view to be able to specify a specific container to be used (not just body).

You might want for example to lazy load images inside a specific div that has a limited height with scrollbars.

What do you think?

cf: https://github.com/vvo/in-viewport#a-custom-container

**Comment by camwiegert** [comment]
@vvo Agreed! I believe @justsml is trying to address this in #18. I'm planning to look at that implementation soon and would like your input.

**Comment by justsml** [comment]
Hey @vvo @camwiegert 

I think I found a bug in the way jQuery's isVisible works:
@vvo passing in a container only works if the parent nodes don't have any of their own `scrollTop` > 0. 
Meaning: only non-scrolling usage or 100% w/h apps --->  no document scroll bars.

https://embed.plnkr.co/FEo1999sz8KWGRH9BHKq/

**Comment by dackmin** [comment]
I follow @vvo on this, as some people can attach handlers to scroll event on `document.body` and call `e.stopPropagation()` at the end, which makes `in-view` not working as intended (or not working at all..)
