### ISSUE TITLE
Set threshold for visibility

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/in-view#21]
Currently, in-view considers an element visible no matter how far into the viewport it is. (>0px) Per @WickyNilliams in #7, it'd be useful to be able to set a custom threshold for visibility. (0-1)

The API is up for discussion, but maybe something like this:

```js
inView.set({
    threshold: 0.5,
    ...
});
```

Or, to match the current offset method:

```js
inView.threshold(0.5);
```

**Comment by camwiegert** [comment]
This should be pretty simple to calculate and basically free, as we get the element height and width from the call to `getBoundingClientRect` that we're already making. 🎉

**Comment by VanBronckhorst** [comment]
Hi, I'd like to help with this if you don't mind. 
Anyway, don't you think this threshold (and maybe the offset as well) should be associated with each selector instead of being global?

**Comment by camwiegert** [comment]
@VanBronckhorst Help is always welcome! And, yes, that's something I've been considering. I like the simplicity of setting offsets and thresholds globally, but maybe we can allow a per-selector offset and threshold that falls back to the global when it isn't set. So...

```js
// Default offset is 50.
inView.offset(50);

// Offset for '.someSelector' is 100.
inView('.someSelector').offset(100);

// Default threshold is 0.
inView.threshold(0);

// Offset for '.someSelector' is 0.5.
inView('.someSelector').threshold(0.5);
```

I'm working on per-direction offset in #22. I'd like to get global threshold and offset to a good place, and then consider extending that to per-selector.

**Comment by WickyNilliams** [comment]
The main thing you need is a function to calculate the area of intersection of two rectangles:

```js
function areaOfIntersection(rectA, rectB) {
  overlapX = Math.max(0, Math.min(rectA.right, rectB.right) - Math.max(rectA.left, rectB.left));
  overlapY = Math.max(0, Math.min(rectA.bottom, rectB.bottom) - Math.max(rectA.top, rectB.top));

  return overlapY * overlapX;
}
```

`a` and `b` should be `DOMRect`-like objects. You can easily get an instance of `DOMRect` for the element itself, as you say, from `getBoundingClientRect()`. For the window, you need to create a duck-typed `DOMRect`, where top and left are `0`, bottom is `window.innerHeight`, and right is `window.innerWidth`.

From here, you can calculate the element's total area (width x height), then divide the area of intersection by total area, then check whether that is `>=` the threshold.

```js
intersectionArea / elementArea >= threshold
```

I agree with @VanBronckhorst these values should be per instance. If you want globals, you should expose the default values, so people can alter them if they wish.

**Comment by WickyNilliams** [comment]
@camwiegert just saw you suggested the same regarding globals :)

The way I've done this before is by simply exposing the defaults as an object. Then you don't need special methods to set them, just mutate the object as you would any other:

```js
inView.defaultOptions = {
  threshold : 50,
  offset : 100
};

// then in user land
inView.defaultOptions.threshold = 1;
```

**Comment by VanBronckhorst** [comment]
The `areaOfIntersection` suggested by @WickyNilliams  works if the threshold is meant to be on the surface of the element, but is that what we want?
The offset is on height and width, not on the surface. If we want to stay consistent with that shouldn't the threshold be on the height and width separately too?

**Comment by WickyNilliams** [comment]
Hmm i'm not sure how offset works, so I can't comment on that. That's the basic algorithm for what I originally suggested anyway. I don't have time to submit a PR, so do with it what you will :)

**Comment by VanBronckhorst** [comment]
![aaa](https://cloud.githubusercontent.com/assets/10037895/18211175/fb392b9a-7101-11e6-80d7-a4ee7d3d96c7.png)

This is roughly what I mean. 
Which of the two percentages is the one the user wants?

**Comment by WickyNilliams** [comment]
Ahh i see. Personally, I'd find the `0.01%` value to be most useful. All I care about is *how much* of an element is visible in total, not how much is visible along each dimension.

If you consider each dimension, the meaning of the threshold value means gets a bit clouded. For instance, if i set the threshold to be `0.5`, intuitively you would assume that it means half the element is visible, but it actually means a quarter.

**Comment by VanBronckhorst** [comment]
I agree with you. I am just not so sure about it because, as I said, the offset works on each dimension separately. 
I think this is a design decision that @camwiegert needs to take.

**Comment by camwiegert** [comment]
@VanBronckhorst @WickyNilliams I'm working on per-direction offset (#22, feedback welcome) at the moment, before getting into this. Threshold is next up. Thanks for getting started. Definitely some considerations here I hadn't thought of.

**Comment by camwiegert** [comment]
@VanBronckhorst @WickyNilliams My instinct is that it's futile to try and calculate the visible surface area considering there could be rounded edges and other styles that affect the technically visible area. So we'd simply say that an element must be in viewport by at least `threshold` in both dimensions. Thoughts?
