### ISSUE TITLE
allow customization of inViewport function

### ISSUE THREAD

**Issue by kmohrf** [camwiegert/in-view#24]
hi and thank you working on this little library :)

i could imagine that in-view would make a perfect scroll-spy library if I’d be able to customize the inViewport function. You’re already exporting the `is` function as part of the libraries interface which gives me the opportunity to implement my own version and just overwrite your version.

unfortunately the registry imports the inViewport function from your module and does not take it as an argument. if you modify to use the `is` function from the interface that should be everything that needs to be done to support this usecase.

thanks in advance

**Comment by camwiegert** [comment]
@kmohrf I think that's a great idea and very worthwhile to implement. I'll put this on the roadmap. Thanks! PR welcome if you'd like.

**Comment by camwiegert** [comment]
@kmohrf And FYI I just pushed `0.4.0`, so keep an eye out for changes.

**Comment by camwiegert** [comment]
This is on the v1 roadmap now as discussed in #27. Closing this issue, but feel free to keep discussing there!

**Comment by kmohrf** [comment]
from my own experience I’m always a bit reluctant when people push decisions to version 1.0 :). 

this is your library and I can use my fork while you keep working on 1.0, but as #25 doesn’t change your existing API and a major version change is intended to allow backwards compatiblity breaks per the semantic version definition, I’d be happy if you reassess your decision to not merge the PR solely based on the rationale that you want to release v1 soon™.
