### ISSUE TITLE
Cannot read property 'top' of undefined(…)

### ISSUE THREAD

**Issue by logol** [camwiegert/in-view#26]
Hey,

`inView('.someSelector').check();`
`inView.is(document.querySelector('.someSelector'));`

both returns: Uncaught TypeError: Cannot read property 'top' of undefined(…)

I am using Chromium 53.0.2785.92 & latest in-view.min.js

**Comment by camwiegert** [comment]
Yup, you're right. That's related to a recent API change. Will be fixing this ASAP. Thanks!

**Comment by camwiegert** [comment]
That should be fixed in `0.4.1`. Thanks again!

**Comment by devloe** [comment]
Seems to be happening again (^0.6.1)
