### ISSUE TITLE
Allow passing a document node or nodelist

### ISSUE THREAD

**Issue by bertez** [camwiegert/in-view#29]
Hi, great module! thanks for your effort!

It would be great if we can also pass an element or array of elements to in-view... something like this:

``` js
inView(document.querySelectorAll('img')).on('enter', function(img) { 
   console.log(img.height);
});
```

what do you think?

**Comment by vvo** [comment]
Ultimately I would not even accept string based selectors. For such a low level library, no magic is fine. Accept only Node or Node Lists :)

**Comment by camwiegert** [comment]
@vvo @bertez I agree, it would be nice to just pass a Node or NodeList.

One nice thing about using string selectors is that we can use it as a key to keep track of registered handlers for that selector.

```js
inView('.selector').on('enter', el =>
    el.classList.add('in-view'));

inView('.selector') // returns the same registry as above
```

If we add the ability to use Node & NodeList, it will be up to the user to maintain a reference to that registry.

```js
const registry = inView(document.querySelectorAll('.selector'));
```

Admittedly, that's not the worst thing in the world. It wouldn't break any existing functionality.

**Comment by pihvi** [comment]
Thanks for this great library!

I'd also like to see an option to pass an Array of nodes as I'm using jQuery and it returns an Array of nodes, not NodeList. This would make jQuery interop much simpler.

**Comment by ghost** [comment]
+1

**Comment by WhereJuly** [comment]
I vote for only one DOM node to pass as @vvo mentioned. The utility size should be kept at the minimum.
