### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by dkdl** [camwiegert/in-view#30]
I get a Uncaught ReferenceError: el is not defined when I call it like this:

    inView('.about video')
      .on('enter', console.log(el) );

Due to restrictions I cannot use the ES6 arrow function. How can I fix this?

**Comment by camwiegert** [comment]
@dkdl You're getting that because you're passing an expression (a function invocation in this case) instead of a function. What you'll want to do is this:

```js
inView('.about video')
    .on('enter', function(el) {
        console.log(el);
        // ...
    });
```

If you just want to log the element, you could do this:
```js
inView('.about video')
    .on('enter',  console.log.bind(console));
```

Hope that helps!

**Comment by dkdl** [comment]
@camwiegert thank you for explaining the problem. I understand now what I did wrong 👍
