### ISSUE TITLE
Offset as a function on the selector 

### ISSUE THREAD

**Issue by SindreSvendby** [camwiegert/in-view#36]
Think the title explains my wish. 

Right now I have done a quick fix that works for me, and that is to change `export default inView()` to `export default inView` so that we can create multiple instance of in-view. See [README](https://github.com/SindreSvendby/in-view/blob/master/README.md) for usage, if people are interested. 

e.g:
```js
inView('.someSelector')
    .offset(100)
    .on('enter', doSomething)
    .on('exit', el => {
        el.style.opacity = 0.5;
    });
```

**Comment by camwiegert** [comment]
@SindreSvendby That is definitely an interface we'd like to implement! Ideally, I'd like to get to a place where each of the global options can be set per-selector. Regarding your fork, keep in mind that multiple in-view instances will create multiple scroll event listeners and may affect performance.

**Comment by gabrielflorit** [comment]
@camwiegert  We also ran into this issue (needing custom offsets). For now I'm doing what @SindreSvendby mentioned, having multiple in-view instances instead of the singleton. Is there an alternative I should explore?
