### ISSUE TITLE
Is it possible to just use lodash.throttle?

### ISSUE THREAD

**Issue by noppanit** [camwiegert/in-view#43]
As far as I have seen I think `in-view` is just using lodash throttle as a dependency. Is it possible to just use `https://www.npmjs.com/package/lodash.throttle`?

**Comment by camwiegert** [comment]
@noppanit Thanks for looking into it! We're actually using a Webpack plugin to accomplish the same thing. ([lodash/lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin))

[webpack.config.js#L25](https://github.com/camwiegert/in-view/blob/master/webpack.config.js#L25)

I believe the bundle is slightly smaller than using modularized lodash, plus it keeps our dependencies a bit simpler.
