### ISSUE TITLE
Option to set threshold based on event

### ISSUE THREAD

**Issue by mackelito** [camwiegert/in-view#44]
It would be really nice to be able to set different threshold for enter and exit.

...some thing like:
```javascript
const onEnter = () => {
  inView.threshold(0.9);
  inView('.item')
    .on('enter', (el) => {
        el.style.visibility = 'visible';
    });
};
const onExit = () => {
  inView.threshold(0.9);
  inView('.item')
    .on('exit', (el) => {
        el.style.visibility = 'hidden';
    });
};
```

**Comment by camwiegert** [comment]
@mackelito Interesting idea. This may be addressed, although not ideally, by the upcoming 1.0 API, which moves settings to each individual registry. So...

```js
inView('.someSelector')
  .set({ threshold: 0.5 })
  .on('enter', someFunc);

inView('.someSelector')
  .set({ threshold: 0.75 })
  .on('exit', someFunc);
```

**Comment by mackelito** [comment]
Looking forward to this! :)

**Comment by mackelito** [comment]
can we keep this open so that I can subscribe and get notified once it has been added? ;)

**Comment by camwiegert** [comment]
Yes, absolutely!

**Comment by mackelito** [comment]
Awesome!
Thx!

**Comment by remikujawski** [comment]
Hi..
Is there any chance for resolve this issue? Non global Threshold?

**Comment by firestar300** [comment]
Any news ?

**Comment by sectsect** [comment]
v1 still pending?

**Comment by sagive** [comment]
I don't understand whats the use of threshold if u cant use it with an event?.. can we append it to the object or something? looking for information about this is frustrating.
