### ISSUE TITLE
Use lodash.throttle exclusively

### ISSUE THREAD

**Issue by stevenvachon** [camwiegert/in-view#45]
https://www.npmjs.com/package/lodash.throttle

**Comment by camwiegert** [comment]
@stevenvachon Right now, we're using [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) to cherry-pick lodash modules.

**Comment by stevenvachon** [comment]
Ah, that's not so bad, but why force the download of the whole thing?

**Comment by camwiegert** [comment]
@stevenvachon Well, only the functions that are imported get into the final bundle. And, believe it or not, the bundle is actually smaller this way 😸

**Comment by stevenvachon** [comment]
:) ok, well I have no argument. Thank you.
