### ISSUE TITLE
Possible to specify different thresholds?

### ISSUE THREAD

**Issue by pushred** [camwiegert/in-view#47]
It doesn't seem possible currently since threshold is set on the function and there's no instantiation happening. If I try to create another "instance" by requiring again and assigning to a different var of course that doesn't work either since it's the same cached function.

Wanted to confirm that this is the case, and if so whether it'd be addressed in the 1.0 API?

I gave IntersectionObserver a shot which supports this since it's an object, but ran into some inconsistent failures in Chrome.. I will say that the API of in-view is far easier to work with in practice than IntersectionObserver was, since it doesn't have much of a notion of exits.

**Comment by camwiegert** [comment]
@pushred You're correct, that's not possible at the moment. But you're in luck, the 1.0 API will be moving all settings to individual registries! I'm hoping to have a release candidate for v1 in the next few weeks.

**Comment by pushred** [comment]
Sweet! Sounds good, thanks
