### ISSUE TITLE
Run MutationObserver on contentLoaded event

### ISSUE THREAD

**Issue by paolocavanna** [camwiegert/in-view#48]
If the script is loaded into the  `<head>`, the instantiation of MutationObserver, done on [line 51 of in-view.js](https://github.com/camwiegert/in-view/blob/master/src/in-view.js#L51), should be done inside a `DOMContentLoaded` event, to prevent the following error:
`Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.`

**Comment by axetroy** [comment]
same with me

**Comment by camwiegert** [comment]
@paolocavanna Thanks for the heads up. Will move to patch this ASAP.

**Comment by camwiegert** [comment]
Alright, this should be all patched in `v0.6.1`. Thanks!

**Comment by paolocavanna** [comment]
Great man!
