### ISSUE TITLE
Add ability to `destroy`

### ISSUE THREAD

**Issue by bekos** [camwiegert/in-view#50]
In single page applications, there are cases we want the `inview` functionality and some others we don't. It would be handy to be able to remove event listeners from page when we want to.

**Comment by camwiegert** [comment]
@bekos Agreed! This is going into the v1 API, which should be ready in 1-2 weeks.

**Comment by losthumans** [comment]
First thank you for this wonderful tiny lib it's great, we needed an 'off' method to deregister all handlers for an event (single page app). You can find the forked branch here: https://github.com/losthumans/in-view Thank you!

**Comment by danielcrisp** [comment]
@losthumans you should create a PR with your fork - it looks good

**Comment by howells** [comment]
Would love @losthumans's PR to be merged, or at least some way of handling listeners. @camwiegert do you know when v1 might be ready? :-)

**Comment by camwiegert** [comment]
@howells Definitely want to get the listener handling issue resolved ASAP! Sorry to keep everyone waiting. I think the fastest path would be completing [v1](https://github.com/camwiegert/in-view/tree/v1). All that remains to be done there is handling options and documentation. 🤞

I've blocked in some time for OSS at the end of this week, so I'm hoping v1 will be ready to go at the beginning of next week.

**Comment by howells** [comment]
@camwiegert awesome, thanks!

**Comment by xiaopow** [comment]
@camwiegert any news about v1?

**Comment by sharq1** [comment]
@camwiegert any chance that you'll be able to release v1 or at least this feature soon?
