### ISSUE TITLE
problem using inView.offset

### ISSUE THREAD

**Issue by erikbue** [camwiegert/in-view#51]
I'm very new to JS, so please excuse this (probably) dumb question.
What is the proper syntax for using .offset? I'm looking to make the color change about 500px after .album-section enters the view. Where would the .offset(500); go?

`inView('.album-section').on('enter', function(el){`

Thanks so much!

**Comment by camwiegert** [comment]
@erikbue Not a dumb question! What you'd likely want is to call in-view's offset method before registering your `enter` handler.

```js
inView.offset(500);
inView('.album-section').on('enter', function(el) {
    // ...
});
```

**Comment by erikbue** [comment]
Ahh gotcha! Thanks!
