### ISSUE TITLE
How to handle dynamically created elements?

### ISSUE THREAD

**Issue by brijeshb42** [camwiegert/in-view#54]
`in-view` works great for selectors already present in the DOM. But how can I detect elements entering/exiting that are created dynamically ?

**Comment by sahandnayebaziz** [comment]
This and #50 are connected as common needs for dynamic pages and single-page applications.

**Comment by mackelito** [comment]
Is there any updates here? :)

**Comment by noppanit** [comment]
We had the same problem and this is a little snippet we did to fix this problem. 

```
var observer = new MutationObserver(function(mutations) {
      mutations.forEach(function(mutation) {
        if (!mutation.addedNodes) {
          return;
        }

        if (document.querySelector(selector)) {
          inView(selector).on('enter', (e) => onEnter(e));
          observer.disconnect();
          return;
        }
      });
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: false,
      characterData: false
    });
```

It is not perfect but it works for us for now. I'm happy to contribute if this is the way to go for the roadmap of the lib.

**Comment by wilr** [comment]
Another work around that seems to work is to also manually trigger a DOMContentLoaded event.
```
window.document.dispatchEvent(new Event("DOMContentLoaded", {
  bubbles: true,
  cancelable: true
}));
```
inView picks this up and updates.
