### ISSUE TITLE
Common error handlings

### ISSUE THREAD

**Issue by krizzu** [camwiegert/in-view#55]
Hey there!  
First of all - great tool! Very useful.  
While playing with it, I've noticed that there is no common error handling. For example, I tried to register an event that do not exist (tried `leave` instead of `exit`).  
Instead of a nice feedback about my error, I saw 
> Cannot read property 'push' of undefined

Which is not very helpful.  

I suggest of adding few lines of checking if passed events/elements etc. are valid, and if not, instead of giving back an error, let's return some proper hint (for example: `Unrecognized event name.`).

**Comment by camwiegert** [comment]
@Krizzu Thanks for bringing this up! That's something that definitely should've been implemented by now. I'll plan to implement this ASAP.

**Comment by krizzu** [comment]
Hey! I think I could take care of that, if it's possible :)
