### ISSUE TITLE
Dependency on lodash

### ISSUE THREAD

**Issue by anseki** [camwiegert/in-view#58]
Copied from https://github.com/camwiegert/in-view/issues/11#issuecomment-273293767 :

> Hi, thank you for the useful library.
> 
> I think, the `lodash` in `package.json` should be moved to `devDependencies` from `dependencies`.
> Some package managers try to install the unneeded `lodash` when the `in-view` is installed. We have to remove it every time.
> All bundled libraries are typically added to `devDependencies`.

Or, is there any reason to be in `dependencies`?

**Comment by camwiegert** [comment]
@anseki I think I agree with you and would merge a PR. That said, the rewrite that I'm finishing up removes the lodash dependency altogether. So, this will be a non-issue soon!
