### ISSUE TITLE
unable to load library before document.body is available

### ISSUE THREAD

**Issue by frko** [camwiegert/in-view#59]
Using webpack and a vendor chunk which we load async in the head is currently impossible due to the document.body.insertBefore statement requiring the body to be available. Deferring the feature testing to 1st usage would remedy the issue in most cases.

Would it be possible to change the implementation to support such a usage pattern ( when http2 push arrives in all browsers this will be the most likely usage pattern for loading js dependencies prolly so it much add to future proofing the library )

**Comment by camwiegert** [comment]
@frko I agree that event binding and feature testing should be deferred until first usage! Thanks for the input and plan to see this in the next release. 👍

**Comment by frko** [comment]
cool, great news! need any help?

**Comment by camwiegert** [comment]
@frko I appreciate the offer, but I'm working (too slowly) on a rewrite that will supplant the current source. I don't want you to put in too much time on something that may get replaced shortly!
