### ISSUE TITLE
Option to set offset per-direction

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/in-view#6]
As it stands, you can only set the offset globally, but it'd be nice to be able to set an offset in each direction, à la:

```js
inView.offset({
    top: 50,
    right: 100
    bottom: 0,
    left: 25
});
```

**Comment by jmeas** [comment]
I was just about to post this issue :)

We implemented this over in [react-waypoint](https://github.com/brigade/react-waypoint) – it's been very useful!

**Comment by davej** [comment]
Also it would be useful to be able to use other units of measurement rather than just pixels. Since this is IE9+ it would be good to be able to use `vh` and `vw`.

**Comment by davidhellmann** [comment]
yes vw / vh would be great!

**Comment by bitmap** [comment]
`vh` / `vw` calculation us pretty simple to hack around. I'm doing this to fake a 50% vertical offset:

```  js
let vh = window.innerHeight;
inView.offset(vh / 2);

window.addEventListener('resize', () => {
  vh = window.innerHeight;
  inView.offset(vh / 2);
});
```

I'll submit a PR when I get some time and build in support for this.
