### ISSUE TITLE
Multiple instances creation

### ISSUE THREAD

**Issue by everyonesdesign** [camwiegert/in-view#60]
I can't find a way to create multiple instances of InView.
'in-view.js' default export allows to get already created instance (see [source](https://github.com/camwiegert/in-view/blob/master/src/in-view.js#L127)). I also can't import InView variable as it's not exported (see [source](https://github.com/camwiegert/in-view/blob/master/src/in-view.js#L8)).

@gabrielflorit mentioned in issue #36 that he deals with the issue via creation of multiple InView objects, but I don't see any way to do this.

I'd suggest the variable exporting, because it seems to be the most non-destructive change.
Thank you.

**Comment by njbarrett** [comment]
I also have a need to create different offsets per selector. Is this something that can be done?

**Comment by everyonesdesign** [comment]
@njbarrett I eventually ended up forking the repo: https://github.com/kudago/in-view
I commited some changes here, maybe I'll create pull request to original repo (or some other person will do it).
You can use it like this:
```js
import InViewFactory from 'kudago-in-view';

const inView1 = InViewFactory();
inView.offset(-100);

const inView2 = InViewFactory();
inView.offset(-200);

// etc...
```

**Comment by njbarrett** [comment]
Thanks heaps for responding - ill check your fork out!

**Comment by gabrielflorit** [comment]
Sorry @everyonesdesign , a bit late to this. Yes, I created my own fork a while back, does the same thing as yours. I'd say, keep using your fork!
