### ISSUE TITLE
Does not work on iPhone 5/5s

### ISSUE THREAD

**Issue by duezerouno** [camwiegert/in-view#66]
Hi all! I am basically using in-view to change section's bg color on scroll. It works flawlessly on every device but the iPhone 5/5s - on this device it just does not work at all. Any idea?

**Comment by camwiegert** [comment]
@duezerouno Could you please provide your code and some more specific info (browser version, OS version) on the environment you're having issues with. Thanks!

**Comment by duezerouno** [comment]
@camwiegert you can have a look to the code here

**Comment by camwiegert** [comment]
@duezerouno Sorry, but I'm not going to dig for your code. If you'd like some help resolving the issue, please post the pertinent code in this thread along with other relevant info and I'll be happy to take a look.

**Comment by duezerouno** [comment]
@camwiegert sorry, was on mobile yesterday :)

as I said I am basically using in-view to animate color background when entering a new section:

```
<article class="section" data-background-color="rgb(66, 159, 155)" id="cosa">
</article>
```
```
var $target = $('#content');
     inView('.section').on('enter', function(el){
     var color = $(el).attr('data-background-color');
     $target.css('background-color', color );
     inView.offset(320);
});
```

this works perfectly everywhere except iPhone 5/5s. Any idea?

**Comment by camwiegert** [comment]
@duezerouno Ahh I think I see your issue. You've set the offset to `320`, which happens to be the width of an iPhone 5 viewport. So, in-view will never consider anything to be in viewport.

What you could do is set your offset by direction...

```js
inView.offset({
  top: 320,
  right: 100,
  bottom: 320,
  left: 100
})
```

..or something like that. Hope that helps!
