### ISSUE TITLE
Zurb Foundation6 : Uncaught TypeError: Cannot set property 'inView'

### ISSUE THREAD

**Issue by studio-sitas** [camwiegert/in-view#68]
Have this error when compiled with Foundation 6 gulp ([Zurb Stack](http://foundation.zurb.com/sites/docs/starter-projects.html)) : 
<img width="347" alt="capture d ecran 2017-06-15 a 11 38 03" src="https://user-images.githubusercontent.com/10993236/27179721-50e85dba-51bf-11e7-99e0-8a6d4b1f840b.png">

**Comment by denkristoffer** [comment]
Where is this `jquery.in-view` from? Is it a part of Foundation? You should probably file an issue with whoever is making that wrapper library.

**Comment by camwiegert** [comment]
As this appears to be an issue with a wrapper library and not in-view itself, I'm going to close this. Feel free to reopen if you learn otherwise.
