### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by alisaleem252** [camwiegert/in-view#69]
I am getting the following error. how can i fix it?

**Comment by camwiegert** [comment]
That would mean that, apparently, there is no `document.body` node. I'd need to see your code to diagnose further.

I'm not sure how that could happen, because `in-view` only attaches the `MutationObserver` on a `DOMContentLoaded` event.

**Comment by alisaleem252** [comment]
Yes you are right. :D i enqueued the script on footer fixed the issue.. :) 
Thanks for your response...
