### ISSUE TITLE
inView.is Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by rgfx** [camwiegert/in-view#70]
Getting this issue local, getting the same issue with reduced case on Codepen

https://codepen.io/rgfx/pen/6c8a714209a4cb5ffb8ca507b3a216e3

**Comment by camwiegert** [comment]
@rgfx in-view doesn't, at the moment, accept raw nodes. Pass your selector string instead:

```js
inView('.hide')
```

**Comment by BeKnowDo** [comment]
This, in fact, is still an issue. 
Doesn't work:
```    const check = inView.is("#category-list-wrapper"); ```
