### ISSUE TITLE
IntersectionObserver support

### ISSUE THREAD

**Issue by shrpne** [camwiegert/in-view#75]
I think it's time to implement IntersectionObserver, since it supported in most modern browsers: http://caniuse.com/#feat=intersectionobserver

**Comment by allenhwkim** [comment]
The link https://wicg.github.io/IntersectionObserver/ is not found

**Comment by johanneslamers** [comment]
Yes!

**Comment by bre7** [comment]
Working link: https://github.com/w3c/IntersectionObserver.

Polyfill: https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill

**Comment by rgfx** [comment]
I found this library that seems to work with intersectionObserver with IE. https://github.com/russellgoldenberg/scrollama

**Comment by mreinstein** [comment]
The only browsers that don't support IntersectionObserver are ie and safari. It's in the technical preview for safari so it's coming. Seems like a really great addition at this point!

**Comment by nathobson** [comment]
Intersection observer has now landed in Safari :)

**Comment by guirreri** [comment]
@camwiegert are there any plans to implement this?

**Comment by nathobson** [comment]
To be perfectly honest, the native Intersection Observer API is so straightforward that it probably makes sense just to use that rather than a library unless you had a particular requirement that the library solves.

**Comment by mreinstein** [comment]
> the native Intersection Observer API is so straightforward that it probably makes 
> sense just to use that rather than a library

Yes, I agree with that. However, `in-view` is an existing library, it's being used in various places already. Ideally it's internal implementation would be as efficient as possible, and adopting intersection observer under the hood means anyone using this library gets better performance automatically. We should be doing this.
