### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by DanielRuf** [camwiegert/in-view#82]
Is this project still actively maintained?

**Comment by youradds** [comment]
It would appear not :/ Looks like I'm going to have to look for another module now, as I've just found out this one doesn't support dynamically added content. Eugh

**Comment by voidgraphics** [comment]
@youradds have you found one? 😄

**Comment by DanielRuf** [comment]
@youradds @voidgraphics see https://github.com/DanielRuf/noopener/blob/master/src/index.js and especially https://davidwalsh.name/detect-node-insertion

**Comment by DanielRuf** [comment]
You can use this to attach new instances to dynamically added elements. Or use `document.attachEventlistener(target, code)` which listens for dynamically added elements.

**Comment by voidgraphics** [comment]
@DanielRuf interesting (and clever) solution by Mr. Walsh, however that does not feel very clean to me. I'd rather use a MutationObserver, which is the solution I am pursuing right now, but I was wondering if there was another in-view library that had this functionality baked-in.

Thank you for your answer 🙂

**Comment by DanielRuf** [comment]
> MutationObserver

https://caniuse.com/#feat=mutationobserver

**Comment by youradds** [comment]
@voidgraphics  I ended up using inview, but when I added dynamic content I then just did this to refresh the DOM elements:

`window.inView('.photo').check();`

Works well for me :)

**Comment by Jetski5822** [comment]
@voidgraphics what did you come up with for mutationobserver?

**Comment by voidgraphics** [comment]
I ended up still using this library and adding another MO on top, but that felt really hacky and dirty so I wouldn't recommend going that route.

I think @youradds's suggestion might be better.

**Comment by Jetski5822** [comment]
I found this one.. https://github.com/russellgoldenberg/scrollama - trying to cut my ties with jQuery and move to be more native. It uses IntrospectionObserver which should be lighter on the site.

**Comment by oelbaga** [comment]
ScrollMagic is probably the next best bet, and it just started to be maintained again after a donation.

**Comment by Jetski5822** [comment]
You actually don’t need any of this anymore. Look at the IntersectionObserver, use that and a polyfill.

I just replaced InView with it and it works, perfectly. Native browser support.

If you run in to problems ping me.

**Comment by Jetski5822** [comment]
Go with Scrollama... it’s uses IntersectionObserver.

Works perfectly
