### ISSUE TITLE
Can we get a non-minified distribution file please?

### ISSUE THREAD

**Issue by marknotton** [camwiegert/in-view#89]
I'm working in an environment that uses Gulp to Minify and Babelfy third party scripts into one compilation. Babel has trouble compiling pre-minified files and is throwing an error...
```
Error in /node_modules/in-view/dist/in-view.min.js:  line Unknown

 Plugin 0 specified in "/node_modules/in-view/package.json" provided an invalid property of "__wrapped__" 
```
In-View currently only has a minified distribution file I can include. I'm not familiar with Webpack, so I'm a bit stuck. 

It would be really handy to have a non-minified `in-view.js`. Any chance you might be able to introduce this in a later update please?

**Comment by oelbaga** [comment]
Can you just use any tool to unminify?

https://unminify.com/
