### ISSUE TITLE
Maybe this is a bad question, but trying to link script on a page yields this:

### ISSUE THREAD

**Issue by apppppppple** [camwiegert/in-view#91]
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://raw.githubusercontent.com/camwiegert/in-view/master/dist/in-view.min.js with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Script:
<script src="https://raw.githubusercontent.com/camwiegert/in-view/master/dist/in-view.min.js"</script>

**Comment by apppppppple** [comment]
How could I make it work?
I know I could copy the plugin code, but I'd like to also have a link to the newest version.

**Comment by dariusrosendahl** [comment]
You need to host it yourself or get it from a CDN. Github is not a CDN :)

**Comment by apppppppple** [comment]
Oh. Thanks!

**Comment by PatrissolJuns** [comment]
I am facing the same problem please @dariusrosendahl do you a CDN where I can host my library for free ?

**Comment by dariusrosendahl** [comment]
I just bundle it with the rest of my Javascript. But the first google result gave me this:

https://www.jsdelivr.com/package/npm/in-view
